name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t react-app .

    - name: Save Docker Image
      run: docker save react-app > react-app.tar

    - name: Copy to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "react-app.tar"
        target: "/home/ubuntu/"

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker load < react-app.tar
          docker stop react-app || true
          docker rm react-app || true
          docker run -d -p 80:80 --name react-app react-app